spring:

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/aluraflix?useSSL=false&createDatabaseIfNotExist=TRUE&allowPublicKeyRetrieval=TRUE&useTimezone=TRUE&serverTimezone=UTC
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
  jpa:   
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    locations: classpath:db/migration,classpath:db/testdata
